# Generated by Django 5.2.5 on 2025-11-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Bachelor of Science in Information Technology', 'BSIT'), ('Bachelor of Science in Computer Science', 'BSCS'), ('Bachelor of Science in Electrical Engineering', 'BSEE'), ('Bachelor of Science in Mechanical Engineering', 'BSME'), ('Bachelor of Science in Nursing', 'BSN'), ('Bachelor of Arts in Communication', 'BA Comm'), ('Bachelor of Science in Business Administration', 'BSBA'), ('Bachelor of Arts in Psychology', 'AB Psychology'), ('Bachelor of Science in Biology', 'BS Biology'), ('Bachelor of Science in Civil Engineering', 'BSCE'), ('Bachelor of Secondary Education', 'BSEd'), ('Bachelor of Arts in English Language Studies', 'ABELS')], default='BSIT')),
                ('start_end_time', models.CharField(max_length=100)),
                ('days_of_week', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('department', models.CharField(choices=[('Bachelor of Science in Information Technology', 'BSIT'), ('Bachelor of Science in Computer Science', 'BSCS'), ('Bachelor of Science in Electrical Engineering', 'BSEE'), ('Bachelor of Science in Mechanical Engineering', 'BSME'), ('Bachelor of Science in Nursing', 'BSN'), ('Bachelor of Arts in Communication', 'BA Comm'), ('Bachelor of Science in Business Administration', 'BSBA'), ('Bachelor of Arts in Psychology', 'AB Psychology'), ('Bachelor of Science in Biology', 'BS Biology'), ('Bachelor of Science in Civil Engineering', 'BSCE'), ('Bachelor of Secondary Education', 'BSEd'), ('Bachelor of Arts in English Language Studies', 'ABELS')], default='BSIT')),
                ('studentIdentifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='profiles/')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('E', 'Enrolled'), ('D', 'Dropped')], default='Pending')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='online_enrollment.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='online_enrollment.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units_earned', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.student')),
            ],
        ),
    ]
