# Generated by Django 5.2.5 on 2025-11-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_delete_testingdatabase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
