# Generated by Django 5.2.5 on 2025-11-21 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_alter_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollmentDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
