# Generated by Django 5.2.7 on 2025-11-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_student_enrollmentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApparelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.CharField(help_text='Unique identifier (e.g., boxy_tee_001)', max_length=50, unique=True)),
                ('style_name', models.CharField(max_length=100, verbose_name='Style Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the style/fit.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active/Visible')),
            ],
            options={
                'verbose_name': 'Apparel Style',
                'verbose_name_plural': 'Apparel Styles',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='The key used in the specs JSONField (e.g., length_in, waist_in)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Garment Length', 'Waist Circumference')", max_length=100)),
                ('unit', models.CharField(help_text='Unit of measure (e.g., in, cm)', max_length=10)),
            ],
            options={
                'verbose_name': 'Measurement Unit Definition',
                'verbose_name_plural': 'Measurement Unit Definitions',
            },
        ),
        migrations.CreateModel(
            name='SizeMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_tag', models.CharField(help_text='The displayed size label (e.g., S, M, L, 32x30)', max_length=20)),
                ('sku_suffix', models.CharField(blank=True, help_text='Suffix used for SKU generation (e.g., S, M, 3230)', max_length=20)),
                ('specs', models.JSONField(default=dict, help_text='Flexible key-value pairs for measurements (e.g., length_in, waist_in).', verbose_name='Measurement Specifications')),
                ('apparel_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='online_enrollment.apparelstyle')),
            ],
            options={
                'verbose_name': 'Size Measurement',
                'verbose_name_plural': 'Size Measurements',
                'ordering': ['apparel_style', 'size_tag'],
                'unique_together': {('apparel_style', 'size_tag')},
            },
        ),
    ]
